### ISSUE TITLE
Nova Apollo/GraphQL got Apollo error during SyncedCron checkScheduledPosts

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1573]
Hi,

During SyncedCron checkScheduledPosts, Nova Apollo/GraphQL generated error and the app is out.

Please find below the error message:
```
{"line":"84","file":"percolatestudio_synced-cron.js","message":"SyncedCron: Not running \"checkScheduledPosts\" again.","time":{"$date":1487893200066},"level":"info"}
{"line":"84","file":"percolatestudio_synced-cron.js","message":"SyncedCron: Not running \"checkScheduledPosts\" again.","time":{"$date":1487893200075},"level":"info"}
Fri Feb 24 2017 00:41:58 GMT+0100 (CET) 'error while server-rendering' 'Error\n    at new ApolloError (/opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:1498:23)\n    at /opt/                 pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:2179:39\n    at /opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:2647:25\n    at Array.for                 Each (native)\n    at /opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/n                 pm/node_modules/apollo-client/apollo.umd.js:2644:27\n    at Array.forEach (nativ                 e)\n    at QueryManager.broadcastQueries (/opt/pm2-meteorEN/smartV3-ASIA-EN/bund                 le/programs/server/npm/node_modules/apollo-client/apollo.umd.js:2641:42)\n    at                  QueryManager.broadcastNewStore (/opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/progra                 ms/server/npm/node_modules/apollo-client/apollo.umd.js:2078:14)\n    at /opt/pm2                 -meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/                 apollo.umd.js:2687:44\n    at Object.dispatch (/opt/pm2-meteorEN/smartV3-ASIA-EN                 /bundle/programs/server/npm/node_modules/redux/lib/applyMiddleware.js:45:18)\n =                 > awaited here:\n    at Function.Promise.await (/opt/pm2-meteorEN/smartV3-ASIA-E                 N/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-pro                 mise/promise_server.js:35:12)\n    at Object.serverOptions.preRender (packages/n                 ova:routing/lib/routing-server.jsx:62:22)\n    at packages/reactrouter:react-rou                 ter-ssr/lib/server.jsx:213:23\n    at [object Object]._.extend.withValue (packag                 es/meteor.js:1122:17)\n    at generateSSRData (packages/reactrouter:react-router                 -ssr/lib/server.jsx:181:29)\n    at sendSSRHtml (packages/reactrouter:react-rout                 er-ssr/lib/server.jsx:107:25)\n    at packages/reactrouter:react-router-ssr/lib/                 server.jsx:94:13\n    at runWithEnvironment (packages/meteor.js:1176:24)\n    at                  packages/meteor.js:1189:14\n    at /opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/pro                 grams/server/npm/node_modules/react-router/lib/match.js:67:5'
{"line":"84","file":"percolatestudio_synced-cron.js","message":"SyncedCron: Not running \"checkScheduledPosts\" again.","time":{"$date":1487893200066},"level":"info"}
{"line":"84","file":"percolatestudio_synced-cron.js","message":"SyncedCron: Not running \"checkScheduledPosts\" again.","time":{"$date":1487893200075},"level":"info"}
Fri Feb 24 2017 00:41:58 GMT+0100 (CET) 'error while server-rendering' 'Error\n    at new ApolloError (/opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:1498:23)\n    at /opt/                 pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:2179:39\n    at /opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/apollo.umd.js:2647:25\n    at Array.for                 Each (native)\n    at /opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/programs/server/n                 pm/node_modules/apollo-client/apollo.umd.js:2644:27\n    at Array.forEach (nativ                 e)\n    at QueryManager.broadcastQueries (/opt/pm2-meteorEN/smartV3-ASIA-EN/bund                 le/programs/server/npm/node_modules/apollo-client/apollo.umd.js:2641:42)\n    at                  QueryManager.broadcastNewStore (/opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/progra                 ms/server/npm/node_modules/apollo-client/apollo.umd.js:2078:14)\n    at /opt/pm2                 -meteorEN/smartV3-ASIA-EN/bundle/programs/server/npm/node_modules/apollo-client/                 apollo.umd.js:2687:44\n    at Object.dispatch (/opt/pm2-meteorEN/smartV3-ASIA-EN                 /bundle/programs/server/npm/node_modules/redux/lib/applyMiddleware.js:45:18)\n =                 > awaited here:\n    at Function.Promise.await (/opt/pm2-meteorEN/smartV3-ASIA-E                 N/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-pro                 mise/promise_server.js:35:12)\n    at Object.serverOptions.preRender (packages/n                 ova:routing/lib/routing-server.jsx:62:22)\n    at packages/reactrouter:react-rou                 ter-ssr/lib/server.jsx:213:23\n    at [object Object]._.extend.withValue (packag                 es/meteor.js:1122:17)\n    at generateSSRData (packages/reactrouter:react-router                 -ssr/lib/server.jsx:181:29)\n    at sendSSRHtml (packages/reactrouter:react-rout                 er-ssr/lib/server.jsx:107:25)\n    at packages/reactrouter:react-router-ssr/lib/                 server.jsx:94:13\n    at runWithEnvironment (packages/meteor.js:1176:24)\n    at                  packages/meteor.js:1189:14\n    at /opt/pm2-meteorEN/smartV3-ASIA-EN/bundle/pro                 grams/server/npm/node_modules/react-router/lib/match.js:67:5'
```

Thank You
Adalidda

**Comment by xavcz** [comment]
It looks like you have a `MongoError`: https://github.com/percolatestudio/meteor-synced-cron/blob/ee6014a3f06130b894a912135f6a41f64889774f/synced-cron-server.js#L205-L212

And normally server-side rendering happens when someone connects to the app, so I don't see how these two things can be related 🤔 

Do you have scheduled posts?

**Comment by adalidda** [comment]
No we don't have schedule posts.

I think that when Nova performs schedule posts or check if there are
schedule posts and in that time, if someone connect to Nova then he/she got
this error. May be Nova should issue a message, Database under maintenance
or something like that.

I don't know if it's important to say, we have about 3,000 posts in our
current database.

Note: when Nova is not checking schedule post or schedule mail, everything
is working fine.

Thank You
Adalidda

**Comment by eric-burel** [comment]
Closed as stale, feel free to reopen
