### ISSUE TITLE
"ENFILE: file table overflow, scandir.. " in example-customization

### ISSUE THREAD

**Issue by genu** [VulcanJS/Vulcan#1619]
There is a problem with the `example-customization` problem

The steps I took:
1. Clone repo
2. Comment out all packages except for `example-customization`
3. `npm install && npm start`

I get the following error:
```
/Users/eugenistoc/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/eugenistoc/github/temp/packages/vulcan-lib'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1535:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/eugenistoc/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at setupClientWatcher (/tools/runners/run-app.js:800:23)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:811:7)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
error Command failed with exit code 1.
```

Any idea what went wrong?

**Comment by meteorplus** [comment]
Are you on windows?

**Comment by genu** [comment]
nope, on OSX

**Comment by zorch** [comment]
+1

**Comment by JackC27** [comment]
/Users/jackcrish/.meteor/packages/templating-compiler/.1.3.2.1ssiw53++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
     'Error: ENFILE: file table overflow, scandir '/Users/jackcrish/Downloads/webdev/Meteor/'...

I received this error after moving my entire project folder to a new folder(Meteor). Doing some googling I came across a fix last year that involved increasing the ulimit. Not sure why I hadn't had to do that the last time I worked on this, but do now. My project is very small still so it seems like overkill.
