### ISSUE TITLE
Can't find npm module 'meteor/vulcan:forms-upload/lib/modules.js'.

### ISSUE THREAD

**Issue by vipinlahoti** [VulcanJS/Vulcan#1635]
Im Trying to add an image upload to Post schema, same as its in instragram example, but all the time gets the following error.

Error: Can't find npm module 'meteor/vulcan:forms-upload/lib/modules.js'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
at Object.require (/Users/vipinlahoti/Documents/Apollo/.meteor/local/build/programs/server/boot.js:200:17)
at options.fallback (packages/modules-runtime.js:479:18)
at require (packages/modules-runtime.js:126:16)
at meteorDir.(anonymous function) (packages/modules.js:62:24)
at fileEvaluate (packages/modules-runtime.js:197:9)
at Module.require (packages/modules-runtime.js:120:16)
at Module.Mp.importSync (/Users/vipinlahoti/.meteor/packages/modules/.0.8.2.1wdgqa5++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
at meteorInstall.node_modules.meteor.vulcan:posts.lib.schema.js (packages/vulcan:posts/lib/schema.js:1:188)
at fileEvaluate (packages/modules-runtime.js:197:9)
at Module.require (packages/modules-runtime.js:120:16)

**Comment by MHerszak** [comment]
I understand this is very late. You are requesting a package in your app which doesn't seem to be registered in your application's (root) package. Did you get this sorted out?
