### ISSUE TITLE
vulcan:lib@1.6.0 not published to Atmosphere package manager

### ISSUE THREAD

**Issue by meshulam** [VulcanJS/Vulcan#1685]
I'm trying to use remote meteor packages for Vulcan, but I'm running into an error trying to install the latest version via `meteor add` in a fresh meteor app:

```
% meteor add vulcan:core@1.6.0
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint vulcan:lib@1.6.0 is not satisfied by vulcan:lib 1.4.0.
Constraints on package "vulcan:lib":
* vulcan:lib@1.6.0 <- vulcan:core 1.6.0
* vulcan:lib@1.6.0 <- vulcan:i18n 1.6.0 <- vulcan:core 1.6.0
* vulcan:lib@1.4.0 <- vulcan:users 1.4.0 <- vulcan:core 1.6.0
* vulcan:lib@1.4.0 <- vulcan:routing 1.4.0 <- vulcan:core 1.6.0

Conflict: Constraint vulcan:users@1.6.0 is not satisfied by vulcan:users 1.4.0.
Constraints on package "vulcan:users":
* vulcan:users@1.6.0 <- vulcan:core 1.6.0

Conflict: Constraint vulcan:routing@1.6.0 is not satisfied by vulcan:routing 1.4.0.
Constraints on package "vulcan:routing":
* vulcan:routing@1.6.0 <- vulcan:core 1.6.0
```

It seems that the 1.6.0 `vulcan:lib` package was never published to Meteor Atmosphere: https://atmospherejs.com/vulcan/lib

Running `meteor add vulcan:core` succeeds, but installs 1.4.0 instead of 1.6.0.

**Comment by SachaG** [comment]
You're right, it wasn't published. Meteor's package management system is a bit buggy and requires defining fixed package versions in order to publish a package sometimes, and I hadn't done that.

**Comment by ErikDakoda** [comment]
I was able to update the Vulcan Atmosphere packages to 1.6.0 but I am experiencing some errors when running the code. It looks to me that vulcan:lib has version 1.6.0 but it contains old code. For example meteor://app/packages/vulcan:lib/lib/modules/headtags.js exports "const Head" instead of "const Headtags".

**Comment by SachaG** [comment]
Oh right, that's actually something I changed recently. I guess I should push a new 1.6.1 version to make sure everything works together.

**Comment by SachaG** [comment]
How about now?

**Comment by meshulam** [comment]
Now I'm getting another error on startup, I'll try reproducing it outside my existing project tonight, but it doesn't seem related to anything I've done:

```
14:02.530(-5)? (STDERR) Error: Invalid definition for displayName field: "bio" is not a supported property
W20170801-08:14:02.531(-5)? (STDERR)     at /Users/matt/code/networkcanvas/vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:910:13
W20170801-08:14:02.531(-5)? (STDERR)     at Function._.each._.forEach (/Users/matt/code/networkcanvas/vulcan/node_modules/underscore/underscore.js:158:9)
W20170801-08:14:02.532(-5)? (STDERR)     at checkAndScrubDefinition (/Users/matt/code/networkcanvas/vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:908:24)
W20170801-08:14:02.533(-5)? (STDERR)     at /Users/matt/code/networkcanvas/vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:487:50
W20170801-08:14:02.533(-5)? (STDERR)     at Function._.each._.forEach (/Users/matt/code/networkcanvas/vulcan/node_modules/underscore/underscore.js:158:9)
W20170801-08:14:02.534(-5)? (STDERR)     at SimpleSchema.extend (/Users/matt/code/networkcanvas/vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:486:28)
W20170801-08:14:02.534(-5)? (STDERR)     at new SimpleSchema (/Users/matt/code/networkcanvas/vulcan/node_modules/simpl-schema/dist/SimpleSchema.js:94:10)
W20170801-08:14:02.535(-5)? (STDERR)     at createCollection (packages/vulcan:lib/lib/modules/collections.js:113:29)
W20170801-08:14:02.535(-5)? (STDERR)     at meteorInstall.node_modules.meteor.vulcan:users.lib.collection.js (packages/vulcan:users/lib/collection.js:10:15)
W20170801-08:14:02.536(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)```

**Comment by SachaG** [comment]
Oh right… it's due to a recent PR. I guess I have to push another update. I'll do it first thing tomorrow :)
