### ISSUE TITLE
Throwing Errors When I Am Adding vulcan:debug Package 

### ISSUE THREAD

**Issue by salimakhtar786** [VulcanJS/Vulcan#1739]
When I added the `vulcan:debug@1.7.0` package into the following package It is generating errors 

```
Package.describe({
  name: "vulcan:base-components",
  summary: "Vulcan components package",
  version: '1.7.0',
  git: "https://github.com/VulcanJS/Vulcan.git"
});

Package.onUse(function (api) {

  api.versionsFrom(['METEOR@1.0']);

  api.use([
    // Vulcan packages
    'reactive-var@1.0.11',
    'vulcan:core@1.7.0',
    'vulcan:posts@1.7.0',
    'vulcan:comments@1.7.0',
    'vulcan:voting@1.7.0',
    'vulcan:accounts@1.7.0',
    'vulcan:categories@1.7.0',
    'vulcan:debug@1.7.0'
  ]);

  api.mainModule("lib/server.js", "server");
  api.mainModule("lib/client.js", "client");

});

```
After adding this `vulcan:debug@1.7.0` package my meteor-app working stop and throwing the following errors at the terminal:
```
/home/deligence/.meteor/packages/meteor-tool/.1.5.1.1mpzie4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Depending on unknown package vulcan:debug
    at Error (native)
    at processUse (/tools/isobuild/package-source.js:1260:15)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/deligence/.meteor/packages/meteor-tool/.1.5.1.1mpzie4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/package-source.js:1270:9
    at Array.forEach (native)
    at Function._.each._.forEach (/home/deligence/.meteor/packages/meteor-tool/.1.5.1.1mpzie4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object]._.extend.getPackagesToLoadFirst (/tools/isobuild/package-source.js:1265:7)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:240:39)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:215:12)
    at /tools/isobuild/isopack-cache.js:243:11
    at Array.forEach (native)
    at Function._.each._.forEach (/home/deligence/.meteor/packages/meteor-tool/.1.5.1.1mpzie4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:242:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:241:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:215:12)
    at /tools/isobuild/isopack-cache.js:243:11
    at Array.forEach (native)
    at Function._.each._.forEach (/home/deligence/.meteor/packages/meteor-tool/.1.5.1.1mpzie4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:242:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:241:20)
    at /tools/isobuild/isopack-cache.js:77:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/deligence/.meteor/packages/meteor-tool/.1.5.1.1mpzie4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:76:24)
    at /tools/project-context.js:844:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:843:18)
    at /tools/project-context.js:285:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:275:18)
    at /tools/project-context.js:267:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:266:13)
    at /tools/runners/run-app.js:563:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:562:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
```
How to fix this?

**Comment by salimakhtar786** [comment]
I have fixed this issue using following steps:

1. Delete the `.meteor/versions` 
2. And restart my app 

I have follow this https://github.com/VulcanJS/Vulcan/issues/1689
