### ISSUE TITLE
Can't add admin package

### ISSUE THREAD

**Issue by Michael-Reich** [VulcanJS/Vulcan#1753]
Added this compoments:

```
    'vulcan:core',

    // 'example-forum',

    // vulcan packages
    'vulcan:posts@1.7.0',
    'vulcan:comments@1.7.0',
    'vulcan:voting@1.7.0',
    'vulcan:accounts@1.7.0',
    'vulcan:admin',
    'vulcan:email',
    'vulcan:forms',
    'vulcan:newsletter',
    'vulcan:notifications',
    'vulcan:getting-started',
    'vulcan:categories',
    'vulcan:events',
    'vulcan:embedly',
    'vulcan:api',
    'vulcan:rss',
    'vulcan:subscribe',

    'vulcan:base-components',
    'vulcan:base-styles',
    'vulcan:email-templates',
```

since I added vulcan:admin I get this error:

```
/xxx/xxx/.meteor/packages/meteor-tool/.1.5.1.1nhwcl7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Depending on unknown package vulcan:admin
    at Error (native)
    at processUse (/tools/isobuild/package-source.js:1260:15)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/michael.reich/.meteor/packages/meteor-tool/.1.5.1.1nhwcl7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/package-source.js:1270:9
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/michael.reich/.meteor/packages/meteor-tool/.1.5.1.1nhwcl7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object]._.extend.getPackagesToLoadFirst (/tools/isobuild/package-source.js:1265:7)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:240:39)
    at /tools/isobuild/isopack-cache.js:77:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/michael.reich/.meteor/packages/meteor-tool/.1.5.1.1nhwcl7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:76:24)
    at /tools/project-context.js:844:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:843:18)
    at /tools/project-context.js:285:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:275:18)
    at /tools/project-context.js:267:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:266:13)
    at /tools/runners/run-app.js:563:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:562:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Vulcan@1.2.0 start: `meteor --settings settings.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Vulcan@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /xxx/xxx/.npm/_logs/2017-10-20T18_32_38_503Z-debug.log
```

**Comment by SachaG** [comment]
Try deleting your `.meteor/versions` file.

**Comment by Michael-Reich** [comment]
Worked! Thank you, can I access Sitemap by this?

**Comment by SachaG** [comment]
No sorry, there's no sitemap package.
