### ISSUE TITLE
sheet.getStyleTags() Is Genarating Error

### ISSUE THREAD

**Issue by salimakhtar786** [VulcanJS/Vulcan#1757]
` sheet.getStyleTags()` is generating error

See the following code

```
if (!options.disableSSR) {
      const sheet = new ServerStyleSheet();
      console.log(sheet.getStyleTags())
      html = renderToString(sheet.collectStyles(app));
      styledComponentCss = sheet.getStyleTags();
    } else if (options.loadingScreen) {
      html = options.loadingScreen;
    }
```
It is generating following error on the terminal:
```
url:  /
I20171024-16:23:57.074(5.5)? [Error: Can't collect styles once you've called getStyleTags!]
W20171024-16:23:57.126(5.5)? (STDERR) Tue Oct 24 2017 16:23:57 GMT+0530 (IST) 'error while server-rendering' 'Error: Can\'t collect styles once you\'ve called getStyleTags!\n    at ServerStyleSheet.collectStyles (/home/deligence/1.Projects/Streetail/node_modules/styled-components/lib/models/ServerStyleSheet.js:116:28)\n    at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:58:35)\n    at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)\n    at packages/vulcan:routing/lib/server/router.jsx:149:11\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/match.js:67:5\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/createTransitionManager.js:108:11\n    at done (/home/deligence/1.Projects/Streetail/node_modules/react-router/lib/AsyncUtils.js:79:19)\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/AsyncUtils.js:85:7\n    at getComponentsForRoute (/home/deligence/1.Projects/Streetail/node_modules/react-router/lib/getComponents.js:11:5)\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/getComponents.js:35:5'
```

**Comment by SachaG** [comment]
Sorry, I haven't used styled components myself yet. Maybe you can ask in the slack chatroom?
