### ISSUE TITLE
Your application is crashing. Waiting for file change.

### ISSUE THREAD

**Issue by enesustundag** [VulcanJS/Vulcan#1871]
Hello there.

I did the uploads as written in the documentation and I ran the npm start command.

the command printed this error after some time in the processor.

```
[[[[[ C:\Users\ENES\Vulcan-Starter ]]]]]

=> Started proxy.
=> Started MongoDB.
{ Error: EPERM: operation not permitted, unlink 'C:\Users\ENES\AppData\Local\Temp\mt-a1iwgs.5bkpn\npm\node_modules\connect'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\ENES\\AppData\\Local\\Temp\\mt-a1iwgs.5bkpn\\npm\\node_modules\\connect' }
boilerplate-generator: updating npm dependencies -- combined-stream2...
```

later 

```

W20180201-14:42:16.383(3)? (STDERR) C:\Users\ENES\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20180201-14:42:20.372(3)? (STDERR)                                             throw(ex);
W20180201-14:42:20.395(3)? (STDERR)                                             ^
W20180201-14:42:20.397(3)? (STDERR)
W20180201-14:42:20.398(3)? (STDERR) TypeError: registerSetting is not a function
W20180201-14:42:20.400(3)? (STDERR)     at utils.js (packages/vulcan:lib/lib/modules/utils.js:16:1)
W20180201-14:42:20.402(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180201-14:42:20.440(3)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180201-14:42:20.442(3)? (STDERR)     at settings.js (packages/vulcan:lib/lib/modules/settings.js:1:232)
W20180201-14:42:20.444(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180201-14:42:20.446(3)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180201-14:42:20.448(3)? (STDERR)     at oauth_config.js (packages/vulcan:lib/lib/server/oauth_config.js:1:29)
W20180201-14:42:20.450(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180201-14:42:20.452(3)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180201-14:42:20.458(3)? (STDERR)     at main.js (packages/vulcan:lib/lib/server/main.js:1:14)
W20180201-14:42:20.461(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180201-14:42:20.463(3)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180201-14:42:20.466(3)? (STDERR)     at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\packages\vulcan_lib.js:4536:15
W20180201-14:42:20.468(3)? (STDERR)     at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\packages\vulcan_lib.js:4543:3
W20180201-14:42:20.473(3)? (STDERR)     at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:411:36
W20180201-14:42:20.475(3)? (STDERR)     at Array.forEach (<anonymous>)
W20180201-14:42:20.476(3)? (STDERR)     at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:220:19
W20180201-14:42:20.478(3)? (STDERR)     at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:471:5
W20180201-14:42:20.482(3)? (STDERR)     at Function.run (C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\profile.js:510:12)
W20180201-14:42:20.485(3)? (STDERR)     at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1
```

When I entered http: // localhost: 3000, I got this error.

```
Your app is crashing. Here's the latest log:
C:\Users\ENES\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
						throw(ex);
						^

TypeError: registerSetting is not a function
    at utils.js (packages/vulcan:lib/lib/modules/utils.js:16:1)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at settings.js (packages/vulcan:lib/lib/modules/settings.js:1:232)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at oauth_config.js (packages/vulcan:lib/lib/server/oauth_config.js:1:29)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at main.js (packages/vulcan:lib/lib/server/main.js:1:14)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\packages\vulcan_lib.js:4536:15
    at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\packages\vulcan_lib.js:4543:3
    at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:411:36
    at Array.forEach (<anonymous>)
    at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:220:19
    at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:471:5
    at Function.run (C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\profile.js:510:12)
    at C:\Users\ENES\Vulcan-Starter\.meteor\local\build\programs\server\boot.js:470:11
Exited with code: 1
Your application is crashing. Waiting for file change.
```

How can i fix the problem?

**Comment by justinr1234** [comment]
You may need to reinstall Meteor after the newer release as they have changed some stuff.

**Comment by SachaG** [comment]
Things to try: 

- make sure you have Meteor 1.6.1.
- delete your `versions` file
- make sure `vulcan:core` in `packages` says 1.8.7 and not 1.8.5
