### ISSUE TITLE
Fresh install from Master branch throws error

### ISSUE THREAD

**Issue by meteorplus** [VulcanJS/Vulcan#1915]
Hi there,

Fresh install from Master branch throws error and break app
```
W20180225-10:12:03.699(0)? (STDERR) Error: "hooks" is Array type but the schema does not include a "hooks.$" definition for the array items"
W20180225-10:12:03.700(0)? (STDERR)     at checkAndScrubDefinition (/home/ubuntu/workspace/xv2/node_modules/simpl-schema/dist/SimpleSchema.js:1139:11)
W20180225-10:12:03.700(0)? (STDERR)     at /home/ubuntu/workspace/xv2/node_modules/simpl-schema/dist/SimpleSchema.js:593:9
W20180225-10:12:03.700(0)? (STDERR)     at Array.forEach (<anonymous>)
W20180225-10:12:03.700(0)? (STDERR)     at SimpleSchema.extend (/home/ubuntu/workspace/xv2/node_modules/simpl-schema/dist/SimpleSchema.js:578:30)
W20180225-10:12:03.700(0)? (STDERR)     at new SimpleSchema (/home/ubuntu/workspace/xv2/node_modules/simpl-schema/dist/SimpleSchema.js:138:10)
W20180225-10:12:03.701(0)? (STDERR)     at createCollection (packages/vulcan:lib/lib/modules/collections.js:120:29)
W20180225-10:12:03.701(0)? (STDERR)     at collection.js (packages/vulcan:debug/lib/modules/callbacks/collection.js:6:19)
W20180225-10:12:03.701(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180225-10:12:03.701(0)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180225-10:12:03.702(0)? (STDERR)     at Callbacks.jsx (packages/vulcan:debug/lib/components/Callbacks.jsx:1:243)
W20180225-10:12:03.702(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180225-10:12:03.702(0)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180225-10:12:03.702(0)? (STDERR)     at components.js (packages/vulcan:debug/lib/modules/components.js:1:221)
W20180225-10:12:03.703(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180225-10:12:03.703(0)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180225-10:12:03.703(0)? (STDERR)     at index.js (packages/vulcan:debug/lib/modules/index.js:1:14)
W20180225-10:12:03.704(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180225-10:12:03.704(0)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180225-10:12:03.704(0)? (STDERR)     at main.js (packages/vulcan:debug/lib/server/main.js:1:14)
W20180225-10:12:03.705(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180225-10:12:03.705(0)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180225-10:12:03.705(0)? (STDERR)     at /home/ubuntu/workspace/xv2/.meteor/local/build/programs/server/packages/vulcan_debug.js:871:15
```

seems it's coming from the debug package

```
  hooks: {
    label: 'Hooks',
    type: Array,
    viewableBy: ['admins'],
    resolveAs: {
      type: '[String]',
      resolver: callback => {
        if (Callbacks[callback.name]) {
          const callbacks = Callbacks[callback.name].map(f => f.name);
          return callbacks;
        } else {
          return [];
        }
      },
    },
  },
```
seems included in core

and also another small error

Error: Cannot find module 'tracker-component'

another one

` Error: "comments" is Array type but the schema does not include a "comments.$" definition for the array items"`

**Comment by SachaG** [comment]
When you say "fresh install from master", do you mean using an example package? Or just running Vulcan with only the core packages? Or something else?

**Comment by meteorplus** [comment]
@SachaG using any of them forum package or simple package or any..

Fresh install I meant clean fork and npm install and running this new version

**Comment by vipinlahoti** [comment]
@meteorplus use [Vulcan-Starter](https://github.com/VulcanJS/Vulcan-Starter) as your base package, will resolve the issue.

**Comment by vipinlahoti** [comment]
@meteorplus user [Vulcan-Starter](https://github.com/VulcanJS/Vulcan-Starter) as your base package resolves the issue.

**Comment by meteorplus** [comment]
@vipinlahoti  I will test that too thanks :)
