### ISSUE TITLE
App crashes when attempt to post same link twice

### ISSUE THREAD

**Issue by bernardodiasc** [VulcanJS/Vulcan#1958]
## How to reproduce

- Create a post including a URL
- Create another post using the same URL

## Expected behaviour

It's expected a friendly error message in the screen.

## Observed behaviour

The app breaks badly.

## Versions

VulcanJS v1.8.9

### Browser console

<img width="707" alt="screen shot 2018-04-19 at 10 12 51 am" src="https://user-images.githubusercontent.com/131859/38993695-b5ce7d8e-43ba-11e8-89e6-02acd900c564.png">

### Server

```
I20180419-09:59:22.713(-3)? // error at callback [PostsNewDuplicateLinksCheck] in hook [posts.new.sync]
I20180419-09:59:22.924(-3)? { posts.link_already_posted
I20180419-09:59:22.924(-3)?     at PostsNewDuplicateLinksCheck (packages/commitlist/lib/server/posts/callbacks/validation.js:49:11)
I20180419-09:59:22.925(-3)?     at packages/vulcan:lib/lib/modules/callbacks.js:82:33
I20180419-09:59:22.925(-3)?     at Array.reduce (<anonymous>)
I20180419-09:59:22.925(-3)?     at runCallbacks (packages/vulcan:lib/lib/modules/callbacks.js:75:22)
I20180419-09:59:22.925(-3)?     at Promise.asyncApply (packages/vulcan:lib/lib/server/mutations.js:89:23)
I20180419-09:59:22.926(-3)?     at /Users/bernardo/.meteor/packages/promise/.0.10.2.jluu88.jxvn++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180419-09:59:22.926(-3)?   name: 'posts.link_already_posted',
I20180419-09:59:22.926(-3)?   _error: Error
I20180419-09:59:22.926(-3)?     at ApolloError.ExtendableError [as constructor] (/Users/bernardo/Sites/commitlist/node_modules/extendable-error/bld/index.js:23:24)
I20180419-09:59:22.926(-3)?     at new ApolloError (/Users/bernardo/Sites/commitlist/node_modules/apollo-errors/dist/index.js:28:28)
I20180419-09:59:22.926(-3)?     at PostsNewDuplicateLinksCheck (packages/commitlist/lib/server/posts/callbacks/validation.js:49:11)
I20180419-09:59:22.927(-3)?     at packages/vulcan:lib/lib/modules/callbacks.js:82:33
I20180419-09:59:22.927(-3)?     at Array.reduce (<anonymous>)
I20180419-09:59:22.927(-3)?     at runCallbacks (packages/vulcan:lib/lib/modules/callbacks.js:75:22)
I20180419-09:59:22.928(-3)?     at Promise.asyncApply (packages/vulcan:lib/lib/server/mutations.js:89:23)
I20180419-09:59:22.928(-3)?     at /Users/bernardo/.meteor/packages/promise/.0.10.2.jluu88.jxvn++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40,
I20180419-09:59:22.928(-3)?   _showLocations: false,
I20180419-09:59:22.929(-3)?   _showPath: false,
I20180419-09:59:22.929(-3)?   time_thrown: '2018-04-19T12:59:22.713Z',
I20180419-09:59:22.929(-3)?   data: { break: true, url: 'http://docs.vulcanjs.org/newsletter.html' } }
W20180419-09:59:22.966(-3)? (STDERR) posts.link_already_posted
W20180419-09:59:22.967(-3)? (STDERR)     at PostsNewDuplicateLinksCheck (packages/commitlist/lib/server/posts/callbacks/validation.js:49:11)
W20180419-09:59:22.967(-3)? (STDERR)     at packages/vulcan:lib/lib/modules/callbacks.js:82:33
W20180419-09:59:22.968(-3)? (STDERR)     at Array.reduce (<anonymous>)
W20180419-09:59:22.968(-3)? (STDERR)     at runCallbacks (packages/vulcan:lib/lib/modules/callbacks.js:75:22)
W20180419-09:59:22.968(-3)? (STDERR)     at Promise.asyncApply (packages/vulcan:lib/lib/server/mutations.js:89:23)
W20180419-09:59:22.968(-3)? (STDERR)     at /Users/bernardo/.meteor/packages/promise/.0.10.2.jluu88.jxvn++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by SachaG** [comment]
It actually looks like it's working properly, although the error can probably be improved to be more user-friendly. Also I think some of the errors in there are unrelated.

**Comment by SachaG** [comment]
I'll push a fix to make it more user-friendly soon :)

![https://d3vv6lp55qjaqc.cloudfront.net/items/2O0o2j3r3E0j2y223M38/Screen%20Shot%202018-04-26%20at%2018.44.23.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=1d84b38c](https://d3vv6lp55qjaqc.cloudfront.net/items/2O0o2j3r3E0j2y223M38/Screen%20Shot%202018-04-26%20at%2018.44.23.png?X-CloudApp-Visitor-Id=f25ee64a8f9b32be400086060540ffac&v=1d84b38c)

**Comment by bernardodiasc** [comment]
I tested this again on v1.9.1 and the frontend no longer crashes on my project. And in fact, some of the bugs reported was unrelated.

Thanks!
