### ISSUE TITLE
http://localhost:3000/components page fails to load when hocs is unspecified

### ISSUE THREAD

**Issue by mousetraps** [VulcanJS/Vulcan#2061]
Reproduced using the `getting-started` and `example-movies` packages in Vulcan-Starter.

Stack trace below. The error occurs when the component is registered as follows (without specifying hocs)
```
registerComponent({ name: 'MoviesItem', component: MoviesItem });
```

Specifying `hocs: []` or separating out into multiple arguments works. 

```
=> App running at: http://localhost:3000/
I20180910-22:38:25.244(-7)? url:  /components
I20180910-22:38:25.267(-7)? { TypeError: Cannot read property 'map' of undefined
I20180910-22:38:25.268(-7)?     at ComponentHOCs (packages/vulcan:debug/lib/components/Components.jsx:11:22)
I20180910-22:38:25.268(-7)?     at walkTree (/Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:716:21)
I20180910-22:38:25.268(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:729:21
I20180910-22:38:25.269(-7)?     at forEachSingleChild (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:881:8)
I20180910-22:38:25.269(-7)?     at traverseAllChildrenImpl (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:785:5)
I20180910-22:38:25.269(-7)?     at traverseAllChildren (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:856:10)
I20180910-22:38:25.269(-7)?     at Object.forEachChildren [as forEach] (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:901:3)
I20180910-22:38:25.269(-7)?     at walkTree (/Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:727:28)
I20180910-22:38:25.269(-7)?     at walkTree (/Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:719:13)
I20180910-22:38:25.269(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:729:21
I20180910-22:38:25.269(-7)?     at forEachSingleChild (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:881:8)
I20180910-22:38:25.270(-7)?     at traverseAllChildrenImpl (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:785:5)
I20180910-22:38:25.270(-7)?     at traverseAllChildrenImpl (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:801:23)
I20180910-22:38:25.270(-7)?     at traverseAllChildrenImpl (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:801:23)
I20180910-22:38:25.270(-7)?     at traverseAllChildren (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:856:10)
I20180910-22:38:25.270(-7)?     at Object.forEachChildren [as forEach] (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:901:3)
I20180910-22:38:25.270(-7)?     at walkTree (/Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:727:28)
I20180910-22:38:25.271(-7)?     at walkTree (/Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:719:13)
I20180910-22:38:25.271(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:729:21
I20180910-22:38:25.272(-7)?     at forEachSingleChild (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:881:8)
I20180910-22:38:25.272(-7)?     at traverseAllChildrenImpl (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:785:5)
I20180910-22:38:25.272(-7)?     at traverseAllChildrenImpl (/Users/itani/src/Vulcan-Starter/node_modules/react/cjs/react.development.js:801:23)
I20180910-22:38:25.272(-7)?  => awaited here:
I20180910-22:38:25.272(-7)?     at Function.Promise.await (/Users/itani/.meteor/packages/promise/.0.11.1.gy8c7h.yyj0f++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180910-22:38:25.272(-7)?     at Object.preRender (packages/vulcan:routing/lib/server/routing.jsx:58:14)
I20180910-22:38:25.273(-7)?     at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:53:15)
I20180910-22:38:25.273(-7)?     at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)
I20180910-22:38:25.273(-7)?     at match (packages/vulcan:routing/lib/server/router.jsx:150:11)
I20180910-22:38:25.273(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/match.js:67:5
I20180910-22:38:25.273(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:108:11
I20180910-22:38:25.273(-7)?     at done (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:79:19)
I20180910-22:38:25.273(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:85:7
I20180910-22:38:25.273(-7)?     at getComponentsForRoute (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/getComponents.js:11:5)
I20180910-22:38:25.274(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/getComponents.js:35:5
I20180910-22:38:25.275(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:84:5
I20180910-22:38:25.275(-7)?     at Array.forEach (<anonymous>)
I20180910-22:38:25.275(-7)?     at mapAsync (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:83:9)
I20180910-22:38:25.275(-7)?     at getComponents (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/getComponents.js:34:28)
I20180910-22:38:25.275(-7)?     at finishEnterHooks (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:102:35)
I20180910-22:38:25.275(-7)?     at runTransitionHooks (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:79:7)
I20180910-22:38:25.276(-7)?     at runEnterHooks (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:112:12)
I20180910-22:38:25.276(-7)?     at /Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:95:7
I20180910-22:38:25.276(-7)?     at runTransitionHooks (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:79:7)
I20180910-22:38:25.276(-7)?     at runChangeHooks (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:136:12)
I20180910-22:38:25.276(-7)?     at finishMatch (/Users/itani/src/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:92:5) queryErrors: [ [Circular] ] }
```

**Comment by mousetraps** [comment]
PR incoming. The fix is two-fold:
1. ensure that hocs gets initialized with an empty array when it's unspecified
2. Update starter examples to use multiple arguments rather than passing in an object (not required after 1, but it's more consistent that way)

**Comment by mousetraps** [comment]
Actually, nevermind - missed this PR :) 
https://github.com/VulcanJS/Vulcan/pull/2031

**Comment by Apollinaire** [comment]
As you pointed out in the issue, #2031 is supposed to solve this issue. 
The syntax  `registerComponent( {name:'MoviesList', component: MoviesList })` is the new syntax since [v1.12.0 ](https://medium.com/@sachagreif/vulcan-js-1-12-a-better-graphql-api-for-crud-operations-fae82e03a7e9#772f), which is why I used this syntax when updating the package example-movies. I think it's good to keep it with the new syntax to help enforce it and avoid teaching the old way to the new people. 
So just wait until @SachaG merges #2031 ;)

**Comment by mousetraps** [comment]
Ahh, I see - thanks! Didn’t realize that was the new syntax. I’ll update the PR to do the opposite, then. I’d assumed the preferred syntax was the one most commonly used in the starter.

Sent from my Rotary Phone

________________________________

**Comment by Apollinaire** [comment]
> I’d assumed the preferred syntax was the one most commonly used in the starter.

Most of the starters have not been updated yet, since v1.12 has been released only 2 weeks ago, but eventually they will be updated and fixed ;)
