### ISSUE TITLE
context.currentUser can be undefined even when user is logged

### ISSUE THREAD

**Issue by lc3t35** [VulcanJS/Vulcan#2181]
Vulcan 1.12.11
User is logged, I had this message when creating a document with mutation
````
DEBUG groups [ 'members' ]
I20190120-17:28:07.826(1)? DEBUG groups [ 'members' ]
I20190120-17:28:14.617(1)? DEBUG mutation context.currentUser undefined  <------ ROOT CAUSE HERE
I20190120-17:28:14.617(1)? DEBUG CanDo authorizedActions []
I20190120-17:28:14.618(1)? DEBUG CanDo actions [ 'information.create', 'informations.new' ]
I20190120-17:28:14.618(1)? DEBUG CanDo intersection []
W20190120-17:28:14.807(1)? (STDERR) app.operation_not_allowed: app.operation_not_allowed
W20190120-17:28:14.808(1)? (STDERR)     at throwError (packages/vulcan:lib/lib/modules/errors.js:108:9)
W20190120-17:28:14.808(1)? (STDERR)     at Object.Utils.performCheck (packages/vulcan:lib/lib/modules/utils.js:499:5)
W20190120-17:28:14.808(1)? (STDERR)     at Promise.asyncApply (packages/vulcan:core/lib/modules/default_mutations.js:66:15)
W20190120-17:28:14.808(1)? (STDERR)     at /Users/laurent/.meteor/packages/promise/.0.11.2.1tzhcqz.ywpql++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
````
I found with debug that `context.currentUser` can be undefined in default_mutation (line 62) : 
````
async mutation(root, {data}, context) {
        const collection = context[collectionName];
        console.log('DEBUG mutation context.currentUser', context.currentUser);
        // check if current user can pass check function; else throw error
        Utils.performCheck(
          this.check,
          context.currentUser,
          data,
          '',
          `${typeName}.create`,
          collectionName
        );
````

If the user reconnects, the canDo works fine as context.currentUser exists, so document is created by mutation
````
DEBUG CanDo authorizedActions [ 'user.create',
I20190120-16:29:06.336(1)?   'user.update.own',
....
I20190120-16:29:06.337(1)?   'information.create',
I20190120-16:29:06.338(1)?   'information.update.own',
I20190120-16:29:06.338(1)?   'information.delete.own,',
.... ]
I20190120-16:29:06.339(1)? DEBUG CanDo actions [ 'information.create', 'informations.new' ]
I20190120-16:29:06.339(1)? DEBUG CanDo intersection [ 'information.create' ]
````

**Comment by lc3t35** [comment]
Here is where the problem happens in apollo_server.js : 
````
if (req.headers.authorization) {
        const token = req.headers.authorization;
        check(token, String);
        const hashedToken = _hashLoginToken(token);

        console.log('DEBUG token', hashedToken, token);
        // Get the user from the database
        user = await Meteor.users.findOne({
          'services.resume.loginTokens.hashedToken': hashedToken,
        });

        console.log('DEBUG user ', user);

        if (user) {
          // identify user to any server-side analytics providers
          runCallbacks('events.identify', user);

          const loginToken = Utils.findWhere(user.services.resume.loginTokens, {
            hashedToken,
          });
          const expiresAt = _tokenExpiration(loginToken.when);
          const isExpired = expiresAt < new Date();

          if (!isExpired) {
            options.context.userId = user._id;
            options.context.currentUser = user;
          }
        }
      }
````

**Comment by lc3t35** [comment]
This happens because "services.resume" is removed ([]) when a new component is loaded ...

**Comment by lc3t35** [comment]
services.resume is removed by previous Accounts.setPassword call : 
````
Accounts.setPassword = (userId, newPlaintextPassword, options) => {
  options = { logout: true , ...options };

  const user = getUserById(userId);
  if (!user) {
    throw new Meteor.Error(403, "User not found");
  }

  const update = {
    $unset: {
      'services.password.srp': 1, // XXX COMPAT WITH 0.8.1.3
      'services.password.reset': 1
    },
    $set: {'services.password.bcrypt': hashPassword(newPlaintextPassword)}
  };

  if (options.logout) {
    update.$unset['services.resume.loginTokens'] = 1;     <<<<<<<======= HERE !
  }

  Meteor.users.update({_id: user._id}, update);
};
````

**Comment by lc3t35** [comment]
Just change `Accounts.setPassword(userId, password, { logout: false });`
