### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string

### ISSUE THREAD

**Issue by lc3t35** [VulcanJS/Vulcan#2308]
After updating to 1.13, I have this error, I was able to remove it when commenting `Components.AccountsLoginForm` in my Login component
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
W20190422-17:25:35.152(2)? (STDERR)     in Login
W20190422-17:25:35.152(2)? (STDERR)     in Query
/.../
W20190422-17:25:35.169(2)? (STDERR)     in Provider
W20190422-17:25:35.170(2)? (STDERR)     in RenderPromisesProvider
W20190422-17:25:35.170(2)? (STDERR) Error while server-rendering. date: Mon Apr 22 2019 17:25:35 GMT+0200 (CEST) url: [object Object]
W20190422-17:25:35.170(2)? (STDERR) { Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
W20190422-17:25:35.171(2)? (STDERR)     at invariant (/Users/***/node_modules/react-dom/cjs/react-dom-server.node.development.js:58:15)
W20190422-17:25:35.171(2)? (STDERR)     at ReactDOMServerRenderer.render (/Users/***/node_modules/react-dom/cjs/react-dom-server.node.development.js:3443:7)
W20190422-17:25:35.171(2)? (STDERR)     at ReactDOMServerRenderer.read (/Users/***/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
W20190422-17:25:35.171(2)? (STDERR)     at renderToString (/Users/***/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
W20190422-17:25:35.171(2)? (STDERR)     at process (/Users/***/node_modules/react-apollo/react-apollo.cjs.js:1043:20)
W20190422-17:25:35.172(2)? (STDERR)     at /Users/laurent/.meteor/packages/promise/.0.11.2.1tzhcqz.ywpql++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20190422-17:25:35.172(2)? (STDERR)  => awaited here:
W20190422-17:25:35.172(2)? (STDERR)     at Function.Promise.await (/Users/laurent/.meteor/packages/promise/.0.11.2.1tzhcqz.ywpql++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20190422-17:25:35.172(2)? (STDERR)     at Promise.asyncApply (packages/vulcan:lib/lib/server/apollo-ssr/renderPage.js:46:16)
W20190422-17:25:35.172(2)? (STDERR)     at /Users/laurent/.meteor/packages/promise/.0.11.2.1tzhcqz.ywpql++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 name: 'Invariant Violation', framesToPop: 1 }
````

**Comment by lc3t35** [comment]
@eric-burel as stated on Slack's channel

**Comment by eric-burel** [comment]
Your `Components` object is not filled at startup for whatever reason, `populateComponentsApp` does not seem to be run. Trying to figure this out right now

**Comment by eric-burel** [comment]
Ok got it you did not upgrade `react-bootstrap` yet, now that it uses v4. Took me some time because I don't use Bootstrap in my own apps. 
<Grid /> is not defined anymore in Bootstrap. It is now named "Container". I suggest following this doc: https://react-bootstrap.github.io/migrating/

Commenting `AccountsLoginForm` should not have solved it though (and it didn't on my version of your app) so there might be an underlying issue.

**Comment by eric-burel** [comment]
I've updated the issue title for our fellow googlers

**Comment by lc3t35** [comment]
Fixed by updating : 
- Grid -> Container
- bsStyle -> variant
- Alert onDismiss -> onClose
