### ISSUE TITLE
Update to 1.13

### ISSUE THREAD

**Issue by lc3t35** [VulcanJS/Vulcan#2333]
Still working on Vulcan's 1.13 migration from 1.12, I have the following error when I launch (2 repo installation)
````
Error while server-rendering. date: Mon Jun 10 2019 12:19:43 GMT+0200 (CEST) url: [object Object]
W20190610-12:19:43.782(2)? (STDERR) SyntaxError: Invalid regular expression: /^\/events\/view((?:\/\:eventId))((?:?\:invitationId))(?:\/(?=$))?$/: Nothing to repeat
W20190610-12:19:43.789(2)? (STDERR)     at new RegExp (<anonymous>)
W20190610-12:19:43.789(2)? (STDERR)     at tokensToRegExp (/xxx/node_modules/react-router/node_modules/path-to-regexp/index.js:394:21)
W20190610-12:19:43.789(2)? (STDERR)     at stringToRegexp (/xxx/node_modules/react-router/node_modules/path-to-regexp/index.js:322:10)
W20190610-12:19:43.790(2)? (STDERR)     at pathToRegexp (/Uxxx/node_modules/react-router/node_modules/path-to-regexp/index.js:425:10)
W20190610-12:19:43.790(2)? (STDERR)     at compilePath (/xxx/node_modules/react-router/matchPath.js:22:39)
W20190610-12:19:43.790(2)? (STDERR)     at matchPath (/xxx/node_modules/react-router/matchPath.js:54:22)
W20190610-12:19:43.790(2)? (STDERR)     at /xxx/node_modules/react-router/Switch.js:75:41
W20190610-12:19:43.791(2)? (STDERR)     at forEachSingleChild (/xxx/node_modules/react/cjs/react.development.js:881:8)
W20190610-12:19:43.791(2)? (STDERR)     at traverseAllChildrenImpl (/xxx/node_modules/react/cjs/react.development.js:785:5)
W20190610-12:19:43.791(2)? (STDERR)     at traverseAllChildrenImpl (/xxx/node_modules/react/cjs/react.development.js:801:23)
W20190610-12:19:43.791(2)? (STDERR)     at traverseAllChildrenImpl (/xxx/node_modules/react/cjs/react.development.js:801:23)
W20190610-12:19:43.792(2)? (STDERR)     at traverseAllChildren (/xxx/node_modules/react/cjs/react.development.js:856:10)
W20190610-12:19:43.792(2)? (STDERR)     at Object.forEachChildren [as forEach] (/xxx/node_modules/react/cjs/react.development.js:901:3)
W20190610-12:19:43.792(2)? (STDERR)     at Switch.render (/xxx/node_modules/react-router/Switch.js:63:30)
W20190610-12:19:43.792(2)? (STDERR)     at processChild (/xxx/react-dom/cjs/react-dom-server.node.development.js:2959:18)
W20190610-12:19:43.793(2)? (STDERR)     at resolve (/xxx/react-dom/cjs/react-dom-server.node.development.js:2812:5)
W20190610-12:19:43.793(2)? (STDERR)     at ReactDOMServerRenderer.render (/xxx/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
W20190610-12:19:43.793(2)? (STDERR)     at ReactDOMServerRenderer.read (/xxx/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
W20190610-12:19:43.793(2)? (STDERR)     at renderToString (/xxx/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
W20190610-12:19:43.794(2)? (STDERR)     at process (/xxxy/node_modules/react-apollo/react-apollo.cjs.js:1044:20)
W20190610-12:19:43.794(2)? (STDERR)     at /Users/laurent/.meteor/packages/promise/.0.11.2.1tzhcqz.ywpql++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20190610-12:19:43.794(2)? (STDERR)  => awaited here:
W20190610-12:19:43.794(2)? (STDERR)     at Function.Promise.await (/Users/laurent/.meteor/packages/promise/.0.11.2.1tzhcqz.ywpql++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20190610-12:19:43.795(2)? (STDERR)     at Promise.asyncApply (packages/vulcan:lib/lib/server/apollo-ssr/renderPage.js:46:16)
W20190610-12:19:43.795(2)? (STDERR)     at /Users/laurent/.meteor/packages/promise/.0.11.2.1tzhcqz.ywpql++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
````

**Comment by ErikDakoda** [comment]
Looks like you might have a malformed route definition that React Router 4 doesn't like. What does your `addRoute` look like for events view?

**Comment by lc3t35** [comment]
Nothing changed here, here is `addroute`
````{ name: "events", path: "/myEvents", componentName: "MyEvents" },````

**Comment by lc3t35** [comment]
thank you @ErikDakoda
