### ISSUE TITLE
"Unexpected token S in JSON at position 0" on Windows 7

### ISSUE THREAD

**Issue by quidama** [VulcanJS/Vulcan#2510]
I tried to start Vucan-starter on Windows7
but there are error like below.
Please help me.

C:\Users\(userId)\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.readMetadataFromDirectory (C:\tools\isobuild\isopack.js:204:28)
    at exports.Tropohouse._alreadyDownloaded (C:\tools\packaging\tropohouse.js:320:19)
    at exports.Tropohouse._makeDownloader (C:\tools\packaging\tropohouse.js:391:33)
    at C:\tools\packaging\tropohouse.js:568:29
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\packaging\tropohouse.js:565:20
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\(userID)\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:561:16)
    at C:\tools\project-context.js:836:25
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\project-context.js:835:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:834:13)
    at C:\tools\project-context.js:300:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
    at Profile.run (C:\tools\project-context.js:282:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
    at C:\tools\runners\run-app.js:547:29
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at bundleApp (C:\tools\runners\run-app.js:546:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:613:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:922:28)
    at C:\tools\runners\run-app.js:401:12
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by eric-burel** [comment]
Sounds like an issue with Meteor-tools, as if a config file was not read correctly. You may need to uninstall/reinstall some package.

Closing because this is not a Vulcan issue but let us know if you keep having trouble

**Comment by eric-burel** [comment]
Maybe this helps https://github.com/meteor/meteor/issues/8467 ?
