### ISSUE TITLE
npm start fails - Invariant Violation

### ISSUE THREAD

**Issue by yehudaRipple** [VulcanJS/Vulcan#2570]
I get the following error on npm start:

W20200511-14:27:09.063(3)? (STDERR) Error while server-rendering. date: Mon May 11 2020 14:27:09 GMT+0300 (Israel Daylight Time) url: [object Object]
W20200511-14:27:09.065(3)? (STDERR) Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.
W20200511-14:27:09.066(3)? (STDERR)     at new InvariantError (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/node_modules/ts-invariant/lib/invariant.js:16:28)
W20200511-14:27:09.066(3)? (STDERR)     at invariant (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/node_modules/ts-invariant/lib/invariant.js:28:15)
W20200511-14:27:09.066(3)? (STDERR)     at QueryData.OperationData.refreshClient (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:62:115)
W20200511-14:27:09.066(3)? (STDERR)     at QueryData.execute (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:147:10)
W20200511-14:27:09.066(3)? (STDERR)     at /home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:509:55
W20200511-14:27:09.066(3)? (STDERR)     at useDeepMemo (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:462:14)
W20200511-14:27:09.067(3)? (STDERR)     at useBaseQuery (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:508:16)
W20200511-14:27:09.067(3)? (STDERR)     at useQuery (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:526:10)
W20200511-14:27:09.067(3)? (STDERR)     at useCurrentUser (packages/vulcan:core/lib/modules/containers/currentUser.js:17:3)
W20200511-14:27:09.067(3)? (STDERR)     at withCurrentUser (packages/vulcan:core/lib/modules/containers/currentUser.js:24:17)
W20200511-14:27:09.067(3)? (STDERR)     at processChild (/home/.../repos/vulcan/Vulcan/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
W20200511-14:27:09.067(3)? (STDERR)     at resolve (/home/.../repos/vulcan/Vulcan/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
W20200511-14:27:09.067(3)? (STDERR)     at ReactDOMServerRenderer.render (/home/.../repos/vulcan/Vulcan/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
W20200511-14:27:09.067(3)? (STDERR)     at ReactDOMServerRenderer.read (/home/.../repos/vulcan/Vulcan/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
W20200511-14:27:09.068(3)? (STDERR)     at renderToStaticMarkup (/home/.../repos/vulcan/Vulcan/node_modules/react-dom/cjs/react-dom-server.node.development.js:4261:27)
W20200511-14:27:09.068(3)? (STDERR)     at process (/home/.../repos/vulcan/Vulcan/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js:38:16)
W20200511-14:27:09.068(3)? (STDERR)     at /home/.../.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200511-14:27:09.068(3)? (STDERR)  => awaited here:
W20200511-14:27:09.068(3)? (STDERR)     at Function.Promise.await (/home/.../.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200511-14:27:09.068(3)? (STDERR)     at packages/vulcan:lib/lib/server/apollo-ssr/renderPage.js:61:7
W20200511-14:27:09.068(3)? (STDERR)     at /home/.../.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 {
W20200511-14:27:09.068(3)? (STDERR)   framesToPop: 1,
W20200511-14:27:09.069(3)? (STDERR)   name: 'Invariant Violation'
W20200511-14:27:09.069(3)? (STDERR) }

**Comment by eric-burel** [comment]
I had it but it disappeared afterward. That's related to "apollo"/react-apoll oversions but not sure of the fix

**Comment by eric-burel** [comment]
Eg https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwjPtLOv-6vpAhUpxoUKHdWCBU8QFjACegQIBRAB&url=https%3A%2F%2Fgithub.com%2Fapollographql%2Freact-apollo%2Fissues%2F3381&usg=AOvVaw2hNYuvPa_hnJmHwit5fj9v
